#!/bin/bash
# https://www.youtube.com/watch?v=hwrnmQumtPw
 
# chmod 755 file-string
 #25:25 227

# Create a file and then if that worked 
#open it in Vim
#     touch samp_file2 # && vim samp_file
#open it in sublime
#     subl samp_file2
# If samp_dir doesn't exist make it
#	    [ -d samp_dir ] || mkdir samp_dir

#### 3. Testing strings   ####  26:53 235
 str1=""
 str2="Sad"
 str3="Happy"
	
# Test if a string is null
	if [ "$str1" ]; then
		echo "$str1 is not null"
	fi
	
	if [ -z "$str1" ]; then
		echo "str1 has no value"
	fi
	
# Check for equality
	if [ "$str2" == "$str3" ]; then
		echo "$str2 equals $str3"
	elif [ "$str2" != "$str3" ]; then
		echo "$str2 is not equal to $str3"
	fi
	
	if [ "$str2" > "$str3" ]; then
		echo "$str2 is greater then $str3"
	elif [ "$str2" < "$str3" ]; then
		echo "$str2 is less then $str3"
	fi


# Check the file test_file1 and test_file2
	file1="./file-strings"
	file2="./test_file2"
	
	if [ -e "$file1" ]; then
		echo "$file1 exists"
		
		if [ -f "$file1" ]; then
			echo "$file1 is a normal file"
		fi
		
		if [ -r "$file1" ]; then
			echo "$file1 is readable"
		fi
		
		if [ -w "$file1" ]; then
			echo "$file1 is writable"
		fi
		
		if [ -x "$file1" ]; then
			echo "$file1 is executable"
		fi
		
		if [ -d "$file1" ]; then
			echo "$file1 is a directory"
		fi
		
		if [ -L "$file1" ]; then
			echo "$file1 is a symbolic link"
		fi
		
		if [ -p "$file1" ]; then
			echo "$file1 is a named pipe"
		fi
		
		if [ -S "$file1" ]; then
			echo "$file1 is a network socket"
		fi
		
		if [ -G "$file1" ]; then
			echo "$file1 is owned by the group"
		fi
		
		if [ -O "$file1" ]; then
			echo "$file1 is owned by the userid"
		fi
		
	fi

echo "End of File scan"	