#!/bin/bash
# https://www.youtube.com/watch?v=hwrnmQumtPw
 
# chmod 755 if-input
 #19:25 169

	
	# You can use read to receive input which is stored in name
	# The p option says that we want to prompt with a string
  	read -p "What is your name? " name
  	echo "Hello $name"
  
  	read -p "How old are you? " age
  	 
  	# You place your condition with in []
  	# Include a space after [ and before ]
  	# Integer Comparisons: eq, ne, le, lt, ge, gt
  	if [ $age -ge 16 ]
  	then
  		echo "You can drive"
  	
  	# Check another condition
  	elif [ $age -eq 15 ]
  	then
  		echo "You can drive next year"
  		
  	# Executed by default
 	else
 	  echo "You can't drive"
 	  
 	# Closes the if statement
 	fi

#  Extended integer test
  	read -p "Enter a number : " num
 	
 	if ((num == 10)); then
 		echo "Your number equals 10"
 	fi
 	
 	if ((num > 10)); then
 		echo "It is greater then 10"
 	else
 		echo "It is less then 10"
 	fi
 	
 	if (( ((num % 2)) == 0 )); then
 		echo " It is even"
 	fi

 	 	# You can use logical operators like &&, || and !
 	if (( ((num > 0)) && ((num < 11)) )); then
 		echo "$num is between 1 and 10"
 	fi
 	
 	# && and || can be used as control structures


   # Read multiple values
  #!/bin/bash
  
  read -p "Enter 2 Numbers to Sum : " num1 num2
  
  sum=$((num1+num2))
  
  echo "$num1 + $num2 = $sum"
  
  # Hide the input with the s code
  read -sp "Enter the Secret Code" secret
  
  if [ "$secret" == "password" ]; then
    echo "Enter"
  else
    echo "Wrong Password"
  fi


# 34:12  343
# $IFS is an  Internal Variables
# Internal Field Separator
# determines how  Bash recognizes fields 
   
  
# Store the original value of IFS
  OIFS="$IFS"
# Set what separates the input values
  IFS=","
read -p "2 numbers separated by a comma" num1 num2
  
# Use the parameter expansion ${} to 
#substitute any whitespace
# with nothing
  num1=${num1//[[:blank:]]/}
  num2=${num2//[[:blank:]]/}
 
  sum=$((num1+num2))
  
  echo "$num1 + $num2 = $sum"
  
  # Reset IFS to the original value
  IFS="$OIFS"
  
  # Parameter expansion allows you to do this
  name="Derek"
  echo "${name}'s Toy"
  
  # The search and replace allows this
  samp_string="The dog climbed the tree"
  echo "${samp_string//dog/cat}"
  
  # You can assign a default value if it doesn't exist
  echo "I am ${name:-Derek}"
  
  # This uses the default if it doesn't exist and assigns the value
  # to the variable
  echo "I am ${name:=Derek}"
  echo $name  

  #39:06  line 380